version: '3'

services:

    node:
        container_name: server
        image: node
        restart: always
        working_dir: /usr/src/app
        ports:
            - 4000:4000
            - 8000:8000
        volumes:
            - ./node/cement-factory:/usr/src/app
        user: $CURRENT_USER
        command: ["yarn", "dev"]

    postgres:
        container_name: postgres
        image: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB

    redis:
        container_name: redis
        image: redis:alpine
        restart: always

    client:
        container_name: client
        image: node
        working_dir: /usr/src/app
        ports:
            - 3000:3000
        volumes:
            - ./clients:/usr/src/app
            - ./node/cement-factory/images:/usr/src/app/assets/images
        user: $CURRENT_USER
        command: ["npx", "lite-server"]
