version: '3'

services:

    node:
        image: node
        restart: always
        working_dir: /usr/src/app
        ports:
            - 4000:4000
            - 8000:8000
        volumes:
            - ./node/cement-factory:/usr/src/app
        user: $CURRENT_USER
        command: ["yarn", "dev"]

    postgres:
        image: postgres
        volumes:
            - ./data:/var/lib/postgresql/data
        restart: always
        environment:
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB

    redis:
        image: redis:alpine
        restart: always
